server:
  port: 8090
spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: STOCK-SERVICE
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/bs/stocks/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka